### ISSUE TITLE
LGv40 Issues with Theme

### ISSUE THREAD

**Issue by DarknessChild** [BakaSai/Oreo-Theme#15]
Running LgV40 With This Theme, Trying to flip systems ui to dark or black results in all notifications being black on black text. Unable to get themes to work on notification shade or settings menu. Even after device hard shutdown and startup.

**Comment by BakaSai** [comment]
@DarknessChild >V40 hahahahahahaha. Not supported thankyouverymuch.

**Comment by DarknessChild** [comment]
» [com.android.settings]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//res/layout/suggestion_tile.xml:11: error: Error: No resource found that matches the given name (at 'layout' with value '@*com.android.settings:layout/horizontal_divider').
» [com.android.settings]: Installation of "com.android.settings" has failed.

**Comment by DarknessChild** [comment]
Any chance of supporting? this damn notification shade is too damn bright!

**Comment by BakaSai** [comment]
@DarknessChild Only way I can do that is if somebody buys me your phone, and even then it's way too much work given what's already on my plate 😅

**Comment by simrat39** [comment]
@BakaSai Sneak 100
